# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#
# Build worker image (VM template)
image: Visual Studio 2015

environment:
  DeployExtension: false
  Package: true

cache:
  - packages -> **\packages.config

configuration: Release

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  nuget restore SlowCheetah.sln

build:
  project: SlowCheetah.sln  # path to Visual Studio solution or project
  verbosity: normal         # MSBuild verbosity level

#---------------------------------#
#       test configuration        #
#---------------------------------#

test:
  assemblies:
    - '**\*tests.dll'

#---------------------------------#
#     artifact configuration      #
#---------------------------------#

artifacts:
  - path: 'bin\**\SlowCheetah*.nupkg'
  - path: 'bin\**\SlowCheetah*.vsix'
  - path: 'bin\**\SlowCheetah*.dll'
  - path: 'bin\**\SlowCheetah*.pdb'
  - path: 'bin\**\SlowCheetah*.targets'

#---------------------------------#
#      deploy configuration       #
#---------------------------------#

# deploy:
#   tag: v$(appveyor_build_version)
#   release: v$(appveyor_build_version)
#   description: 'SlowCheetah NuGet package and VSIX'
#   provider: GitHub
#   auth_token:
#     secure: z+T+CuFrnl/PoGwwnSx5G/xBEPAzjoW5xoUicVUSH8aUHU7OXESK90d8+wxQxc4Y   # your encrypted token from GitHub
#   artifact: /bin\/.*\/SlowCheetah.*\.(nupkg|vsix)/   # upload slow cheetah nupkg and vsix
#   draft: false
#   prerelease: false
#   on:
#     branch: master                 # release from master branch only
#     appveyor_repo_tag: true        # deploy on tag push only
